server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cards
    username: postgres
    password: ***
  liquibase:
    change-log: classpath:liguibase/changelog-master.yml

